name: Deploy
on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
        description: "Target Environment"
      runner-group:
        required: true
        type: string
        description: "Target Runner Group"
      runner-label:
        required: true
        type: string
        description: "Target Runner Label"
      release-action:
        required: true
        type: string
        description: "Release Action"

jobs:

  pre-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Pre-deploy ${{ inputs.release-action }} Release"
      run: |
        echo "Release should be ${{ inputs.release-action }}"
      if: inputs.release-action != ''

  deploy:
    needs: [pre-deploy]
    name: "Deploy on ${{ inputs.target-env }}"
    uses: CasaVian/actions-demos/.github/workflows/cd-deploy.yml@main
    with:
      target-env: ${{ inputs.target-env }}
      runner-group: ${{ inputs.runner-group }}
      runner-label: ${{ inputs.runner-label }}

  post-deploy:
    needs: [deploy]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target-env }}
    steps:
    - name: "Post-deploy ${{ inputs.release-action }} Release"
      run: |
        echo "Release should be ${{ inputs.release-action }}"
      if: inputs.release-action != ''
