name: Promote
on:
  workflow_call:
    inputs:
      envs:
        required: true
        type: string
        description: "Environments (stringified JSON)"
        defaults: '[ { "env":"Dev", "runner-group": "on-prem-non-prod", "runner-label": "app-01" }, { "env":"Uat", "release": "open", "runner-group": "on-prem-sub-prod", "runner-label": "app-01" }, { "env":"Prod", "release": "close", "runner-group": "on-prem-prod", "runner-label": "app-01" } ]'

jobs:
  orchestrate:
    strategy:
      matrix:
        target: ${{ fromJSON( inputs.envs ) }}
      fail-fast: true
      max-parallel: 1
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.target.env }}
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: "${{ matrix.target.release }} Release"
      run: |
        echo "Release should be ${{ matrix.target.release }}"
      if: matrix.target.release != ''

  deploy:
    strategy:
      matrix:
        target: ${{ fromJSON( inputs.envs ) }}
    name: "Deploy on ${{ matrix.target.env }}"
    uses: CasaVian/actions-demos/.github/workflows/cd-deploy-env.yml@main
    with:
      target-env: ${{ matrix.target.env }}
      target-group: ${{ matrix.target.runner-group }}
      target-label: ${{ matrix.target.runner-label }}
