name: Promote
on:
  workflow_call:
    inputs:
      envs:
        required: true
        type: string
        description: "Environments (stringified JSON)"

jobs:
  promote:
    strategy:
      matrix:
        target: ${{ fromJSON( inputs.envs ) }}
      fail-fast: true
      max-parallel: 1
    uses: CasaVian/actions-demos/.github/workflows/cd-env.yml@main
    with:
      target-env: ${{ matrix.target.env }}
      runner-group: ${{ matrix.target.runner-group }}
      runner-label: ${{ matrix.target.runner-label }}
      release-action: ${{ matrix.target.release-action }}
